package menus;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class CafeAdmin extends CafeWindow {
    
    public CafeAdmin() {
        initComponents();
        designComponents();
        loadDatabaseTables();
        displayWindow();
    }
    
    @Override
    public void displayWindow() {
        initializeWindow(this);
        setVisible(true);
    }

    @Override
    public void closeWindow() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        javax.swing.JPanel pnlLeft = new javax.swing.JPanel();
        javax.swing.JLabel lblProducts = new javax.swing.JLabel();
        javax.swing.JButton btnUpdateProduct = new javax.swing.JButton();
        javax.swing.JButton btnAddProduct = new javax.swing.JButton();
        tfInStock = new javax.swing.JTextField();
        tfProductId = new javax.swing.JTextField();
        tfProductName = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        javax.swing.JLabel lblInStock = new javax.swing.JLabel();
        javax.swing.JLabel lblProductId = new javax.swing.JLabel();
        javax.swing.JLabel lblProductName = new javax.swing.JLabel();
        javax.swing.JLabel lblPrice = new javax.swing.JLabel();
        scrlProducts = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        javax.swing.JButton btnShop = new javax.swing.JButton();
        javax.swing.JButton btnReloadDatabase = new javax.swing.JButton();
        javax.swing.JButton btnExit = new javax.swing.JButton();
        javax.swing.JLabel lblLogo = new javax.swing.JLabel();
        javax.swing.JButton btnDeleteProduct = new javax.swing.JButton();
        javax.swing.JPanel pnlRight = new javax.swing.JPanel();
        javax.swing.JLabel lblOrders = new javax.swing.JLabel();
        javax.swing.JPanel pnlMenu = new javax.swing.JPanel();
        scrlUsers = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        scrlOrders = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        tfSearchUsers = new javax.swing.JTextField();
        javax.swing.JButton btnSearchUsers = new javax.swing.JButton();
        tfSearchOrders = new javax.swing.JTextField();
        javax.swing.JButton btnSearchOrders = new javax.swing.JButton();
        javax.swing.JButton btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JButton btnExecute = new javax.swing.JButton();
        cbOperator = new javax.swing.JComboBox<>();
        cbCondition = new javax.swing.JComboBox<>();
        cbTable = new javax.swing.JComboBox<>();
        cbColumn = new javax.swing.JComboBox<>();
        cbFunction = new javax.swing.JComboBox<>();
        javax.swing.JLabel lblEqual = new javax.swing.JLabel();
        javax.swing.JLabel lblWhere = new javax.swing.JLabel();
        javax.swing.JLabel lblFrom = new javax.swing.JLabel();
        javax.swing.JLabel lblOf = new javax.swing.JLabel();
        javax.swing.JLabel lblRetrieve = new javax.swing.JLabel();
        tfConditionValue = new javax.swing.JTextField();
        javax.swing.JLabel wdwBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Brewed & Blended");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAll.setBackground(new java.awt.Color(229, 195, 183));
        pnlAll.setMaximumSize(new java.awt.Dimension(1359, 750));
        pnlAll.setMinimumSize(new java.awt.Dimension(1359, 750));
        pnlAll.setPreferredSize(new java.awt.Dimension(1359, 750));
        pnlAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(219, 173, 157));
        pnlLeft.setOpaque(false);
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProducts.setBackground(new java.awt.Color(255, 255, 255));
        lblProducts.setFont(new java.awt.Font("Hug Me Tight", 0, 26)); // NOI18N
        lblProducts.setForeground(new java.awt.Color(127, 81, 89));
        lblProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducts.setText("- Products -");
        pnlLeft.add(lblProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 300, -1));

        btnUpdateProduct.setBackground(new java.awt.Color(244, 227, 214));
        btnUpdateProduct.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnUpdateProduct.setForeground(new java.awt.Color(127, 81, 89));
        btnUpdateProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/update.png"))); // NOI18N
        btnUpdateProduct.setText("Update");
        btnUpdateProduct.setToolTipText("Updates an existing product's details in the database. ");
        btnUpdateProduct.setBorder(null);
        btnUpdateProduct.setBorderPainted(false);
        btnUpdateProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateProduct.setFocusCycleRoot(true);
        btnUpdateProduct.setFocusPainted(false);
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });
        pnlLeft.add(btnUpdateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 102, 40));

        btnAddProduct.setBackground(new java.awt.Color(244, 227, 214));
        btnAddProduct.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(127, 81, 89));
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        btnAddProduct.setText("Add");
        btnAddProduct.setToolTipText("Adds the inputted product above to the database.");
        btnAddProduct.setBorder(null);
        btnAddProduct.setBorderPainted(false);
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.setFocusCycleRoot(true);
        btnAddProduct.setFocusPainted(false);
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        pnlLeft.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 102, 40));

        tfInStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfInStock.setForeground(new java.awt.Color(127, 81, 89));
        tfInStock.setToolTipText("0 for False, 1 for True");
        pnlLeft.add(tfInStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 60, 34));

        tfProductId.setEditable(false);
        tfProductId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfProductId.setForeground(new java.awt.Color(127, 81, 89));
        tfProductId.setFocusable(false);
        pnlLeft.add(tfProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 40, 34));

        tfProductName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfProductName.setForeground(new java.awt.Color(127, 81, 89));
        pnlLeft.add(tfProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 170, 34));

        tfPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfPrice.setForeground(new java.awt.Color(127, 81, 89));
        pnlLeft.add(tfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 70, 34));

        lblInStock.setBackground(new java.awt.Color(255, 255, 255));
        lblInStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInStock.setForeground(new java.awt.Color(127, 81, 89));
        lblInStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInStock.setText("InStock");
        pnlLeft.add(lblInStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 60, 30));

        lblProductId.setBackground(new java.awt.Color(255, 255, 255));
        lblProductId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductId.setForeground(new java.awt.Color(127, 81, 89));
        lblProductId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductId.setText("Id");
        pnlLeft.add(lblProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 30));

        lblProductName.setBackground(new java.awt.Color(255, 255, 255));
        lblProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(127, 81, 89));
        lblProductName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductName.setText("Name");
        pnlLeft.add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 70, 30));

        lblPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(127, 81, 89));
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrice.setText("Price");
        pnlLeft.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 70, 30));

        tblProducts.setAutoCreateRowSorter(true);
        tblProducts.setBackground(new java.awt.Color(219, 173, 157));
        tblProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblProducts.setForeground(new java.awt.Color(255, 255, 255));
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price", "InStock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducts.setFocusable(false);
        tblProducts.setGridColor(new java.awt.Color(255, 255, 255));
        tblProducts.setInheritsPopupMenu(true);
        tblProducts.setRequestFocusEnabled(false);
        tblProducts.setRowHeight(25);
        tblProducts.setSelectionBackground(new java.awt.Color(127, 81, 89));
        tblProducts.setShowGrid(true);
        tblProducts.setSurrendersFocusOnKeystroke(true);
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        scrlProducts.setViewportView(tblProducts);
        if (tblProducts.getColumnModel().getColumnCount() > 0) {
            tblProducts.getColumnModel().getColumn(0).setResizable(false);
            tblProducts.getColumnModel().getColumn(1).setResizable(false);
            tblProducts.getColumnModel().getColumn(2).setResizable(false);
            tblProducts.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlLeft.add(scrlProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 370, 300));

        btnShop.setBackground(new java.awt.Color(244, 227, 214));
        btnShop.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnShop.setForeground(new java.awt.Color(127, 81, 89));
        btnShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/shop.png"))); // NOI18N
        btnShop.setText("Shop");
        btnShop.setToolTipText("Directs to the Shop.");
        btnShop.setBorder(null);
        btnShop.setBorderPainted(false);
        btnShop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShop.setFocusCycleRoot(true);
        btnShop.setFocusPainted(false);
        btnShop.setMaximumSize(new java.awt.Dimension(49, 17));
        btnShop.setMinimumSize(new java.awt.Dimension(49, 17));
        btnShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShopActionPerformed(evt);
            }
        });
        pnlLeft.add(btnShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 110, 40));

        btnReloadDatabase.setBackground(new java.awt.Color(244, 227, 214));
        btnReloadDatabase.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnReloadDatabase.setForeground(new java.awt.Color(127, 81, 89));
        btnReloadDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/load.png"))); // NOI18N
        btnReloadDatabase.setText("Reload");
        btnReloadDatabase.setToolTipText("Reloads the database tables.");
        btnReloadDatabase.setBorder(null);
        btnReloadDatabase.setBorderPainted(false);
        btnReloadDatabase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReloadDatabase.setFocusCycleRoot(true);
        btnReloadDatabase.setFocusPainted(false);
        btnReloadDatabase.setMaximumSize(new java.awt.Dimension(49, 17));
        btnReloadDatabase.setMinimumSize(new java.awt.Dimension(49, 17));
        btnReloadDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadDatabaseActionPerformed(evt);
            }
        });
        pnlLeft.add(btnReloadDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 110, 40));

        btnExit.setBackground(new java.awt.Color(244, 227, 214));
        btnExit.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(127, 81, 89));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setToolTipText("Exits the Program.");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusCycleRoot(true);
        btnExit.setFocusPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlLeft.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 102, 40));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        pnlLeft.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 40, 290, 90));

        btnDeleteProduct.setBackground(new java.awt.Color(244, 227, 214));
        btnDeleteProduct.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnDeleteProduct.setForeground(new java.awt.Color(127, 81, 89));
        btnDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        btnDeleteProduct.setText("Delete");
        btnDeleteProduct.setToolTipText("Deletes the inputted product above from the database.");
        btnDeleteProduct.setBorder(null);
        btnDeleteProduct.setBorderPainted(false);
        btnDeleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteProduct.setFocusCycleRoot(true);
        btnDeleteProduct.setFocusPainted(false);
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 100, 40));

        pnlAll.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 760));

        pnlRight.setBackground(new java.awt.Color(219, 173, 157));
        pnlRight.setOpaque(false);
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrders.setBackground(new java.awt.Color(255, 255, 255));
        lblOrders.setFont(new java.awt.Font("Hug Me Tight", 0, 32)); // NOI18N
        lblOrders.setForeground(new java.awt.Color(127, 81, 89));
        lblOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrders.setText("- Orders -");
        pnlRight.add(lblOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 230, 60));

        pnlMenu.setBackground(new java.awt.Color(219, 173, 157));
        pnlMenu.setOpaque(false);
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlRight.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tblUsers.setAutoCreateRowSorter(true);
        tblUsers.setBackground(new java.awt.Color(219, 173, 157));
        tblUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblUsers.setForeground(new java.awt.Color(255, 255, 255));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "FirstName", "LastName", "Username", "Email", "ContactNo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setFocusable(false);
        tblUsers.setGridColor(new java.awt.Color(255, 255, 255));
        tblUsers.setInheritsPopupMenu(true);
        tblUsers.setRequestFocusEnabled(false);
        tblUsers.setRowHeight(25);
        tblUsers.setSelectionBackground(new java.awt.Color(127, 81, 89));
        tblUsers.setShowGrid(true);
        scrlUsers.setViewportView(tblUsers);
        if (tblUsers.getColumnModel().getColumnCount() > 0) {
            tblUsers.getColumnModel().getColumn(0).setResizable(false);
            tblUsers.getColumnModel().getColumn(1).setResizable(false);
            tblUsers.getColumnModel().getColumn(2).setResizable(false);
            tblUsers.getColumnModel().getColumn(3).setResizable(false);
            tblUsers.getColumnModel().getColumn(4).setResizable(false);
            tblUsers.getColumnModel().getColumn(5).setResizable(false);
        }

        pnlRight.add(scrlUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 670, 130));

        tblOrders.setAutoCreateRowSorter(true);
        tblOrders.setBackground(new java.awt.Color(219, 173, 157));
        tblOrders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblOrders.setForeground(new java.awt.Color(255, 255, 255));
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderId", "UserId", "ProductId", "Quantity", "TotalAmount", "OrderDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.setFocusable(false);
        tblOrders.setGridColor(new java.awt.Color(255, 255, 255));
        tblOrders.setInheritsPopupMenu(true);
        tblOrders.setRequestFocusEnabled(false);
        tblOrders.setRowHeight(25);
        tblOrders.setSelectionBackground(new java.awt.Color(127, 81, 89));
        tblOrders.setShowGrid(true);
        scrlOrders.setViewportView(tblOrders);
        if (tblOrders.getColumnModel().getColumnCount() > 0) {
            tblOrders.getColumnModel().getColumn(0).setResizable(false);
            tblOrders.getColumnModel().getColumn(1).setResizable(false);
            tblOrders.getColumnModel().getColumn(2).setResizable(false);
            tblOrders.getColumnModel().getColumn(3).setResizable(false);
            tblOrders.getColumnModel().getColumn(4).setResizable(false);
            tblOrders.getColumnModel().getColumn(5).setResizable(false);
        }

        pnlRight.add(scrlOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 670, 140));

        tfSearchUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfSearchUsers.setForeground(new java.awt.Color(127, 81, 89));
        tfSearchUsers.setText("Enter UserId or Username");
        tfSearchUsers.setToolTipText("");
        tfSearchUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSearchUsersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfSearchUsersMouseExited(evt);
            }
        });
        pnlRight.add(tfSearchUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 560, 40));

        btnSearchUsers.setBackground(new java.awt.Color(244, 227, 214));
        btnSearchUsers.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnSearchUsers.setForeground(new java.awt.Color(127, 81, 89));
        btnSearchUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        btnSearchUsers.setText("Search");
        btnSearchUsers.setToolTipText("Searches for the inputted Id or Username in the textfield.");
        btnSearchUsers.setBorder(null);
        btnSearchUsers.setBorderPainted(false);
        btnSearchUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchUsers.setFocusCycleRoot(true);
        btnSearchUsers.setFocusPainted(false);
        btnSearchUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUsersActionPerformed(evt);
            }
        });
        pnlRight.add(btnSearchUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 102, 40));

        tfSearchOrders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfSearchOrders.setForeground(new java.awt.Color(127, 81, 89));
        tfSearchOrders.setText("Enter Id or Date (yyyy-mm-dd)");
        tfSearchOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSearchOrdersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfSearchOrdersMouseExited(evt);
            }
        });
        pnlRight.add(tfSearchOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 560, 40));

        btnSearchOrders.setBackground(new java.awt.Color(244, 227, 214));
        btnSearchOrders.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnSearchOrders.setForeground(new java.awt.Color(127, 81, 89));
        btnSearchOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        btnSearchOrders.setText("Search");
        btnSearchOrders.setToolTipText("Searches for the inputted Id in the textfield.");
        btnSearchOrders.setBorder(null);
        btnSearchOrders.setBorderPainted(false);
        btnSearchOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchOrders.setFocusCycleRoot(true);
        btnSearchOrders.setFocusPainted(false);
        btnSearchOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOrdersActionPerformed(evt);
            }
        });
        pnlRight.add(btnSearchOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 102, 40));

        btnLogout.setBackground(new java.awt.Color(244, 227, 214));
        btnLogout.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(127, 81, 89));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setToolTipText("Exits the Shop.");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusCycleRoot(true);
        btnLogout.setFocusPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlRight.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 630, 120, 40));
        pnlRight.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 670, 20));

        btnExecute.setBackground(new java.awt.Color(244, 227, 214));
        btnExecute.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnExecute.setForeground(new java.awt.Color(127, 81, 89));
        btnExecute.setText("Execute");
        btnExecute.setToolTipText("Searches for the inputted Id in the textfield.");
        btnExecute.setBorder(null);
        btnExecute.setBorderPainted(false);
        btnExecute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExecute.setFocusCycleRoot(true);
        btnExecute.setFocusPainted(false);
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });
        pnlRight.add(btnExecute, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 102, 40));

        cbOperator.setForeground(new java.awt.Color(127, 81, 89));
        cbOperator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<", ">=", "<=" }));
        pnlRight.add(cbOperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 50, 30));

        cbCondition.setForeground(new java.awt.Color(127, 81, 89));
        cbCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Column-", "ProductId", "ProductName", "Price", "InStock", "OrderId", "Quantity", "TotalAmount", "OrderDate", "UserId", "FirstName", "LastName", "Username", "Email", "ContactNo" }));
        pnlRight.add(cbCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, 30));

        cbTable.setForeground(new java.awt.Color(127, 81, 89));
        cbTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Table-", "products", "orders", "users" }));
        pnlRight.add(cbTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, 30));

        cbColumn.setForeground(new java.awt.Color(127, 81, 89));
        cbColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Column-", "*", "ProductId", "ProductName", "Price", "InStock", "OrderId", "Quantity", "TotalAmount", "OrderDate", "UserId", "FirstName", "LastName", "Username", "Email", "ContactNo" }));
        pnlRight.add(cbColumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 110, 30));

        cbFunction.setForeground(new java.awt.Color(127, 81, 89));
        cbFunction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Function-", "SUM", "COUNT", "AVG", "MIN", "MAX" }));
        pnlRight.add(cbFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 90, 30));

        lblEqual.setBackground(new java.awt.Color(255, 255, 255));
        lblEqual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEqual.setForeground(new java.awt.Color(127, 81, 89));
        lblEqual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEqual.setText("IS ");
        pnlRight.add(lblEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 30, 20));

        lblWhere.setBackground(new java.awt.Color(255, 255, 255));
        lblWhere.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWhere.setForeground(new java.awt.Color(127, 81, 89));
        lblWhere.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWhere.setText("WHERE");
        pnlRight.add(lblWhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 60, 20));

        lblFrom.setBackground(new java.awt.Color(255, 255, 255));
        lblFrom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFrom.setForeground(new java.awt.Color(127, 81, 89));
        lblFrom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrom.setText("FROM");
        pnlRight.add(lblFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 50, 20));

        lblOf.setBackground(new java.awt.Color(255, 255, 255));
        lblOf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOf.setForeground(new java.awt.Color(127, 81, 89));
        lblOf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOf.setText("OF");
        pnlRight.add(lblOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 30, 20));

        lblRetrieve.setBackground(new java.awt.Color(255, 255, 255));
        lblRetrieve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRetrieve.setForeground(new java.awt.Color(127, 81, 89));
        lblRetrieve.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRetrieve.setText("RETRIEVE");
        pnlRight.add(lblRetrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 70, 20));

        tfConditionValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfConditionValue.setForeground(new java.awt.Color(127, 81, 89));
        pnlRight.add(tfConditionValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 70, 30));

        pnlAll.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 790, 770));

        wdwBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/adminBg.png"))); // NOI18N
        wdwBg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(wdwBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        String productName = tfProductName.getText();
        String productPrice = tfPrice.getText();
        String productInStock = tfInStock.getText();
        
        // If the product textfields are empty, show error; else, ask for confirmation to add product
        if (tfProductName.getText().isEmpty() || tfPrice.getText().isEmpty() || tfInStock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in all the Product details.","No/Lacking Details Inputted",JOptionPane.ERROR_MESSAGE);
        } 
        else if (JOptionPane.showConfirmDialog(null, "Are you sure you want to add " +productName+ 
                " with the price of " +productPrice+ " to the database?", "Add New Product?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();

                // Check if product exists within the database; if yes, show error; if not, then add new product with entered details
                String query;
                query = "SELECT * FROM products WHERE ProductName='"+productName+"';";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()){
                    JOptionPane.showMessageDialog(this,"Product already exists within the database. \nPlease double-check the inputted product name.",
                        "Product Addition Unsuccessful",JOptionPane.ERROR_MESSAGE);
                    // Clear product textfields
                    clearProductTextFields();
                    System.out.print("Update of product unsuccessfull!");
                } else{
                    query = "INSERT INTO products (ProductName, Price, InStock) VALUES ('"+productName+"', "+productPrice+", "+productInStock+");";
                    st.executeUpdate(query);
                    // Update database tables in the program
                    loadDatabaseTables();
                    JOptionPane.showMessageDialog(this,productName + " successfully added to the database! Click the Load button below to view.",
                        "Product Addition Successful",JOptionPane.INFORMATION_MESSAGE);
                    // Clear product textfields
                    clearProductTextFields();
                    System.out.println("Product successfully added!");
                }
                con.close();
            } catch (HeadlessException | ClassNotFoundException | SQLException e){
                    System.out.println("Error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        String productId = tfProductId.getText();
        String productName = tfProductName.getText();
        String productPrice = tfPrice.getText();
        String productInStock = tfInStock.getText();
        
        // If all product textfields except for tfProductId and tfInStock are filled in, update InStock
        if (tfProductId.getText().isEmpty() == false && tfProductName.getText().isEmpty() && tfPrice.getText().isEmpty() && tfInStock.getText().isEmpty() == false){
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want to update the availability of Product Id "
                +productId+" in the database?", "Update product availability?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try { 
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                    String user = "root";
                    String pass = "";
                    Connection con = DriverManager.getConnection(url,user,pass);
                    Statement st = con.createStatement();

                    // Check if product exists within the database; if yes, then update; if not, then null
                    String query;
                    query = "SELECT * FROM products WHERE ProductId="+productId+";";
                    ResultSet rs = st.executeQuery(query);
                    if (rs.next()){
                        query = "UPDATE products SET InStock="+productInStock+" WHERE ProductId="+productId+";";
                        st.executeUpdate(query);
                        // Update database tables in the program
                        loadDatabaseTables();
                        JOptionPane.showMessageDialog(this,"Product Id "+productId+"'s availability successfully updated!",
                            "Product Availability Update Successful",JOptionPane.INFORMATION_MESSAGE);
                        // Clear product textfields
                        clearProductTextFields();
                        System.out.println("Product availability successfully updated!");
                    } else{
                        JOptionPane.showMessageDialog(this,"Product does not seem to exist within the database. \nPlease double-check the inputted product name.",
                            "Product Availability Update Unsuccessful",JOptionPane.ERROR_MESSAGE);
                        // Clear product textfields
                        clearProductTextFields();
                        System.out.print("Update of product availability unsuccessfull!");
                    }
                    con.close();
                } catch (HeadlessException | ClassNotFoundException | SQLException e){
                        System.out.println("Error " + e.getMessage());
                        System.out.print("Update of product availability unsuccessfull!");
                }
            }
        } // If the product textfields are empty, show error; else, ask for confirmation to update product details
        else if (tfProductId.getText().isEmpty() || tfProductName.getText().isEmpty() || tfPrice.getText().isEmpty()|| tfInStock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in all the Product details.","No/Lacking Details Inputted",JOptionPane.ERROR_MESSAGE);
        } 
        else if (JOptionPane.showConfirmDialog(null, "Are you sure you want to update the details of the product in Product Id "
                +productId+" in the database?", "Update product details?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();

                // Check if product exists within the database; if yes, then update; if not, then null
                String query;
                query = "SELECT * FROM products WHERE ProductId="+productId+";";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()){
                    query = "UPDATE products SET InStock="+productInStock+", Price="+productPrice+", ProductName='"+productName+"' WHERE ProductId="+productId+";";
                    st.executeUpdate(query);
                    // Update database tables in the program
                    loadDatabaseTables();
                    JOptionPane.showMessageDialog(this,productName + " details successfully updated!",
                        "Product Price Update Successful",JOptionPane.INFORMATION_MESSAGE);
                    // Clear product textfields
                    clearProductTextFields();
                    System.out.println("Product price successfully updated!");
                } else{
                    JOptionPane.showMessageDialog(this,"Product does not seem to exist within the database. \nPlease double-check the inputted product name.",
                        "Product Price Update Unsuccessful",JOptionPane.ERROR_MESSAGE);
                    // Clear product textfields
                    clearProductTextFields();
                    System.out.print("Update of product price unsuccessfull!");
                }
                con.close();
            } catch (HeadlessException | ClassNotFoundException | SQLException e){
                    System.out.println("Error " + e.getMessage());
                    System.out.print("Update of product price unsuccessfull!");
            }
        }
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        String productId = tfProductId.getText();
        String productName = tfProductName.getText();
        
        // If the product textfields are empty, show error; else, ask for confirmation to delete product
        if (tfProductId.getText().isEmpty() || tfProductName.getText().isEmpty() || tfPrice.getText().isEmpty() || tfInStock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in all the Product details.","No/Lacking Details Inputted",JOptionPane.ERROR_MESSAGE);
        }
        else if (JOptionPane.showConfirmDialog(null, "Are you sure you want to delete "+productName+ 
                " from the database? This cannot be undone.", "Delete Product?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();
                
                // Check if product exists within the database; if yes, then delete; if not, then null
                String query;
                query = "SELECT * FROM products WHERE ProductId="+productId+";";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()){
                    query = "DELETE FROM products WHERE ProductId="+productId+";";
                    st.executeUpdate(query);
                    // Update database tables in the program
                    loadDatabaseTables();
                    JOptionPane.showMessageDialog(this,productName + " successfully deleted from the database!",
                        "Product Deletion Successful",JOptionPane.INFORMATION_MESSAGE);
                    // Clear product textfields
                    clearProductTextFields();
                    System.out.println("Product successfully deleted!");
                } else{
                    JOptionPane.showMessageDialog(this,"Product does not seem to exist within the database. \nPlease double-check the inputted product name.",
                        "Product Deletion Unsuccessful",JOptionPane.ERROR_MESSAGE);
                    // Clear product textfields
                    clearProductTextFields();
                    System.out.print("Deletion of product unsuccessfull!");
                }
                con.close();
            } catch (HeadlessException | ClassNotFoundException | SQLException e){
                System.out.println("Error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Shop?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            closeWindow();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShopActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Go to Shop?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new CafeMenu().setVisible(true);
            closeWindow();
        }
    }//GEN-LAST:event_btnShopActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Shop?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            closeWindow();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnReloadDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadDatabaseActionPerformed
        loadDatabaseTables();
    }//GEN-LAST:event_btnReloadDatabaseActionPerformed

    private void btnSearchOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOrdersActionPerformed
        if (tfSearchOrders.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please input item to search.","No Details Inputted",JOptionPane.ERROR_MESSAGE);
        } else {
            try { 
                //Clear the Orders table
                DefaultTableModel ordersModel = (DefaultTableModel)tblOrders.getModel();
                ordersModel.setRowCount(0);
                    
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();
                
                // Check if entered text matches with any values in the database; if yes, then show in Orders table; if not, show error
                String search = tfSearchOrders.getText();
                String query = "SELECT * FROM orders WHERE OrderId="+search+" OR UserId="+search+" OR ProductId="+search+";";
                ResultSet rs = st.executeQuery(query);
                while (rs.next()){
                        String orderId = String.valueOf(rs.getInt("OrderId"));
                        String userId = String.valueOf(rs.getInt("UserId"));
                        String productId = String.valueOf(rs.getInt("ProductId"));
                        String productQty = String.valueOf(rs.getInt("Quantity"));
                        String totalAmount = String.valueOf(rs.getDouble("TotalAmount"));
                        String orderDate = String.valueOf(rs.getString("OrderDate"));

                        String tbData[] = {orderId, userId, productId, productQty, totalAmount, orderDate};
                        ordersModel.addRow(tbData); 
                }
                //If looking for orders within a specific date
                query = "SELECT * FROM orders WHERE OrderDate LIKE '"+search+"%';";
                System.out.println(query);
                rs = st.executeQuery(query);
                while (rs.next()){
                        String orderId = String.valueOf(rs.getInt("OrderId"));
                        String userId = String.valueOf(rs.getInt("UserId"));
                        String productId = String.valueOf(rs.getInt("ProductId"));
                        String productQty = String.valueOf(rs.getInt("Quantity"));
                        String totalAmount = String.valueOf(rs.getDouble("TotalAmount"));
                        String orderDate = String.valueOf(rs.getString("OrderDate"));

                        String tbData[] = {orderId, userId, productId, productQty, totalAmount, orderDate};
                        ordersModel.addRow(tbData); 
                } 
                int resultsRows = tblOrders.getRowCount();
                JOptionPane.showMessageDialog(this,resultsRows+" results matching query.",
                        "Query Search Results",JOptionPane.INFORMATION_MESSAGE);
                con.close();
            } catch (Exception e){
                int resultsRows = tblOrders.getRowCount();
                JOptionPane.showMessageDialog(this,resultsRows+" results matching query.",
                        "Query Search Results",JOptionPane.ERROR_MESSAGE);
                System.out.println("Error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSearchOrdersActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Exit Shop?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new CafeLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUsersActionPerformed
        if (tfSearchUsers.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please input item to search.","No Details Inputted",JOptionPane.ERROR_MESSAGE);
        } else {
            try { 
                // Clear the Users table
                DefaultTableModel usersModel = (DefaultTableModel)tblUsers.getModel();
                usersModel.setRowCount(0);
                    
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();
                
                // Check if entered text matches with any Username in the database; if yes, then show in Users table; if not, show error
                String search = tfSearchUsers.getText();
                String query = "SELECT * FROM users WHERE Username='"+search+"';";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()){
                        String userId = String.valueOf(rs.getInt("UserId"));
                        String firstName = String.valueOf(rs.getString("FirstName"));
                        String lastName = String.valueOf(rs.getString("LastName"));
                        String username = String.valueOf(rs.getString("Username"));
                        String email = String.valueOf(rs.getString("Email"));
                        String contactNo = String.valueOf(rs.getString("ContactNo"));

                        String tbData[] = {userId, firstName, lastName, username, email, contactNo};
                        usersModel.addRow(tbData); 
                } else {
                    System.out.println("No Username matches.");
                }
                
                // Check if entered text matches with any UserId in the database; if yes, then show in Users table; if not, show error
                query = "SELECT * FROM users WHERE UserId="+search+";";
                rs = st.executeQuery(query);
                if (rs.next()){
                        String userId = String.valueOf(rs.getInt("UserId"));
                        String firstName = String.valueOf(rs.getString("FirstName"));
                        String lastName = String.valueOf(rs.getString("LastName"));
                        String username = String.valueOf(rs.getString("Username"));
                        String email = String.valueOf(rs.getString("Email"));
                        String contactNo = String.valueOf(rs.getString("ContactNo"));

                        String tbData[] = {userId, firstName, lastName, username, email, contactNo};
                        usersModel.addRow(tbData); 
                } else {
                    System.out.println("No User Id matches.");
                    JOptionPane.showMessageDialog(this,"User does not seem to exist within the database. \nPlease double-check the inputted username.",
                        "Username Search Unsuccessful",JOptionPane.ERROR_MESSAGE);
                }
                int resultsRows = tblUsers.getRowCount();
                JOptionPane.showMessageDialog(this,resultsRows+" results matching query.",
                        "Query Search Results",JOptionPane.INFORMATION_MESSAGE);
                
                con.close();
            } catch (Exception e){
                System.out.println("Error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSearchUsersActionPerformed

    private void tfSearchOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchOrdersMouseClicked
        if (tfSearchOrders.getText().equals("Enter Id or Date (yyyy-mm-dd)"))
            tfSearchOrders.setText("");
    }//GEN-LAST:event_tfSearchOrdersMouseClicked

    private void tfSearchUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchUsersMouseClicked
        if (tfSearchUsers.getText().equals("Enter UserId or Username"))
            tfSearchUsers.setText("");
    }//GEN-LAST:event_tfSearchUsersMouseClicked

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        String function = cbFunction.getSelectedItem().toString();
        String column = cbColumn.getSelectedItem().toString();
        String table = cbTable.getSelectedItem().toString();
        String conditionColumn = cbCondition.getSelectedItem().toString();
        String operator = cbOperator.getSelectedItem().toString();
        String conditionValue = tfConditionValue.getText();
        
        try { 
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url,user,pass);
            Statement st = con.createStatement();
            
            // If no condition is selected or stated
            if (conditionColumn.equals("-Column-") || conditionValue.equals("")){
                String query = "SELECT "+function+"("+column+") FROM "+table+";";
                System.out.println(query);
                ResultSet rs = st.executeQuery(query);
                ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
                int columnsNumber = rsmd.getColumnCount();
                StringBuilder sb = new StringBuilder();

                while (rs.next()) {
                    for (int i = 1; i <= columnsNumber; i++) {
                        String columnValue = rs.getString(i);
                        sb.append(rsmd.getColumnName(i)).append(": ").append(columnValue).append(" ");
                    }
                    sb.append("\n");
                }
                if (sb.length() > 0) {
                    JOptionPane.showMessageDialog(this, sb.toString(), "Query Result", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No results found.", "Query Result", JOptionPane.INFORMATION_MESSAGE);
                }
            } else { // If condition is selected or stated
                String query = "SELECT "+function+"("+column+") FROM "+table+" WHERE "+conditionColumn+operator+conditionValue+";";
                System.out.println(query);
                ResultSet rs = st.executeQuery(query);
                ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
                int columnsNumber = rsmd.getColumnCount();
                StringBuilder sb = new StringBuilder();

                while (rs.next()) {
                    for (int i = 1; i <= columnsNumber; i++) {
                        String columnValue = rs.getString(i);
                        sb.append(rsmd.getColumnName(i)).append(": ").append(columnValue).append(" ");
                    }
                sb.append("\n");
                }
                if (sb.length() > 0) {
                    JOptionPane.showMessageDialog(this, sb.toString(), "Query Result", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "No results found.", "Query Result", JOptionPane.INFORMATION_MESSAGE);
                }
            } 
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "SQL Error: The query seems to be incomplete or incorrect.\nPlease double-check.", "Query Unsuccessful", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: The query seems to be incomplete or incorrect.\nPlease double-check.", "Query Unsuccessful", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        int row = tblProducts.getSelectedRow();
        String productId = tblProducts.getValueAt(row,0).toString();
        String productName = tblProducts.getValueAt(row,1).toString();
        String productPrice = tblProducts.getValueAt(row,2).toString();
        String productInStock = tblProducts.getValueAt(row,3).toString();
        
        // Get the details of the row selected in Products table and paste it to the product textfields
        tfProductId.setText(productId);
        tfProductName.setText(productName);
        tfPrice.setText(productPrice);
        tfInStock.setText(productInStock);
    }//GEN-LAST:event_tblProductsMouseClicked

    private void tfSearchUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchUsersMouseExited
        if (tfSearchUsers.getText().equals(""))
            tfSearchUsers.setText("Enter UserId or Username");
    }//GEN-LAST:event_tfSearchUsersMouseExited

    private void tfSearchOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchOrdersMouseExited
        if (tfSearchOrders.getText().equals(""))
            tfSearchOrders.setText("Enter Id or Date (yyyy-mm-dd)");
    }//GEN-LAST:event_tfSearchOrdersMouseExited
 
    private void designComponents() {
        // Cart design
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer)tblOrders.getDefaultRenderer(Object.class);
        renderer.setHorizontalAlignment( SwingConstants.CENTER );
        
        tblProducts.getTableHeader().setOpaque(false);
        tblProducts.getTableHeader().setForeground(new Color(127,81,89));
        tblProducts.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        tblProducts.getColumnModel().getColumn(0).setMaxWidth(35);
        tblProducts.getColumnModel().getColumn(1).setMaxWidth(350);
        tblProducts.getColumnModel().getColumn(2).setMaxWidth(75);
        tblProducts.getColumnModel().getColumn(3).setMaxWidth(75);
        
        tblOrders.getTableHeader().setOpaque(false);
        tblOrders.getTableHeader().setForeground(new Color(127,81,89));
        tblOrders.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        tblOrders.getColumnModel().getColumn(0).setMaxWidth(75);
        tblOrders.getColumnModel().getColumn(1).setMaxWidth(75);
        tblOrders.getColumnModel().getColumn(2).setMaxWidth(100);
        tblOrders.getColumnModel().getColumn(3).setMaxWidth(75);
        tblOrders.getColumnModel().getColumn(4).setMaxWidth(150);
        tblOrders.getColumnModel().getColumn(5).setMaxWidth(250);
        
        tblUsers.getTableHeader().setOpaque(false);
        tblUsers.getTableHeader().setForeground(new Color(127,81,89));
        tblUsers.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        tblUsers.getColumnModel().getColumn(0).setMaxWidth(35);
        tblUsers.getColumnModel().getColumn(1).setMaxWidth(150);
        tblUsers.getColumnModel().getColumn(2).setMaxWidth(110);
        tblUsers.getColumnModel().getColumn(3).setMaxWidth(100);
        tblUsers.getColumnModel().getColumn(4).setMaxWidth(200);
        tblUsers.getColumnModel().getColumn(5).setMaxWidth(110);
    }
    
    private void clearProductTextFields(){
        tfProductId.setText("");
        tfProductName.setText("");
        tfPrice.setText("");
        tfInStock.setText("");
    }
    
    private void loadDatabaseTables(){
        try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();

                // Clear the Products table
                DefaultTableModel productsModel = (DefaultTableModel)tblProducts.getModel();
                productsModel.setRowCount(0);
                // Get data from Products database
                String query = "SELECT * FROM products";
                ResultSet rs = st.executeQuery(query);
                while(rs.next()){
                    String productId = String.valueOf(rs.getInt("ProductId"));
                    String productName = String.valueOf(rs.getString("ProductName"));
                    String price = String.valueOf(rs.getDouble("Price"));
                    String inStock = String.valueOf(rs.getInt("InStock"));
                    
                    String tbData[] = {productId,productName,price,inStock};
                    productsModel.addRow(tbData); 
                }
                
                // Clear the Orders table
                DefaultTableModel ordersModel = (DefaultTableModel)tblOrders.getModel();
                ordersModel.setRowCount(0);
                // Get data from Orders database
                query = "SELECT * FROM orders";
                rs = st.executeQuery(query);
                while(rs.next()){
                    String orderId = String.valueOf(rs.getInt("OrderId"));
                    String userId = String.valueOf(rs.getInt("UserId"));
                    String productId = String.valueOf(rs.getInt("ProductId"));
                    String productQty = String.valueOf(rs.getInt("Quantity"));
                    String totalAmount = String.valueOf(rs.getDouble("TotalAmount"));
                    String orderDate = String.valueOf(rs.getString("OrderDate"));
                    
                    String tbData[] = {orderId,userId,productId,productQty,totalAmount,orderDate};
                    ordersModel = (DefaultTableModel)tblOrders.getModel();
                    ordersModel.addRow(tbData); 
                }
                
                // Clear the Users table
                DefaultTableModel usersModel = (DefaultTableModel)tblUsers.getModel();
                usersModel.setRowCount(0);
                // Get data from Users database
                query = "SELECT * FROM users";
                rs = st.executeQuery(query);
                while(rs.next()){
                    String userId = String.valueOf(rs.getInt("UserId"));
                    String firstName = String.valueOf(rs.getString("FirstName"));
                    String lastName = String.valueOf(rs.getString("LastName"));
                    String username = String.valueOf(rs.getString("Username"));
                    String email = String.valueOf(rs.getString("Email"));
                    String contactNo = String.valueOf(rs.getString("ContactNo"));
                    
                    String tbData[] = {userId,firstName,lastName,username,email,contactNo};
                    usersModel = (DefaultTableModel)tblUsers.getModel();
                    usersModel.addRow(tbData); 
                } 
                con.close();
                System.out.println("Database tables successfully loaded!");
            } catch (Exception e){
                System.out.println("Error " + e.getMessage());
                System.out.print("Loading of database tables unsuccessfull!");
            }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CafeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbColumn;
    private javax.swing.JComboBox<String> cbCondition;
    private javax.swing.JComboBox<String> cbFunction;
    private javax.swing.JComboBox<String> cbOperator;
    private javax.swing.JComboBox<String> cbTable;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JScrollPane scrlOrders;
    private javax.swing.JScrollPane scrlProducts;
    private javax.swing.JScrollPane scrlUsers;
    public static javax.swing.JTable tblOrders;
    public static javax.swing.JTable tblProducts;
    public static javax.swing.JTable tblUsers;
    private javax.swing.JTextField tfConditionValue;
    public javax.swing.JTextField tfInStock;
    public javax.swing.JTextField tfPrice;
    public javax.swing.JTextField tfProductId;
    public javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfSearchOrders;
    private javax.swing.JTextField tfSearchUsers;
    // End of variables declaration//GEN-END:variables
}
