package menus;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class CafeMenu extends CafeWindow {

    /**
     * Creates new form CafeMenu
     */
    public CafeMenu() {
        initComponents();
        designComponents();
        matchMenuToDatabase();
        displayWindow();
    }
    
    @Override
    public void displayWindow() {
        initializeWindow(this);
        setVisible(true);
    }

    @Override
    public void closeWindow() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        javax.swing.JPanel pnlLeft = new javax.swing.JPanel();
        javax.swing.JLabel lblLogo = new javax.swing.JLabel();
        javax.swing.JLabel lblCart = new javax.swing.JLabel();
        scrlCart = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        javax.swing.JButton btnDelete = new javax.swing.JButton();
        javax.swing.JButton btnClear = new javax.swing.JButton();
        javax.swing.JButton btnBuy = new javax.swing.JButton();
        javax.swing.JLabel lblReceipt = new javax.swing.JLabel();
        scrlReceipt = new javax.swing.JScrollPane();
        areaReceipt = new javax.swing.JTextArea();
        btnAdmin = new javax.swing.JButton();
        javax.swing.JButton btnPrint = new javax.swing.JButton();
        areaTotalPrice = new javax.swing.JTextField();
        javax.swing.JButton btnExit = new javax.swing.JButton();
        javax.swing.JPanel pnlRight = new javax.swing.JPanel();
        javax.swing.JPanel pnlMenu = new javax.swing.JPanel();
        javax.swing.JLabel lblDessert = new javax.swing.JLabel();
        javax.swing.JLabel lblCoffee = new javax.swing.JLabel();
        javax.swing.JLabel lblNoncoffee = new javax.swing.JLabel();
        p2_AddToCart = new javax.swing.JButton();
        p2_Qty = new javax.swing.JSpinner();
        p2_Price = new javax.swing.JLabel();
        p3_Price = new javax.swing.JLabel();
        p3_Qty = new javax.swing.JSpinner();
        p3_AddToCart = new javax.swing.JButton();
        p1_Qty = new javax.swing.JSpinner();
        p1_AddToCart = new javax.swing.JButton();
        p1_Price = new javax.swing.JLabel();
        p4_Price = new javax.swing.JLabel();
        p4_Qty = new javax.swing.JSpinner();
        p4_AddToCart = new javax.swing.JButton();
        p5_Qty = new javax.swing.JSpinner();
        p5_AddToCart = new javax.swing.JButton();
        p5_Price = new javax.swing.JLabel();
        p6_Qty = new javax.swing.JSpinner();
        p6_Price = new javax.swing.JLabel();
        p6_AddToCart = new javax.swing.JButton();
        p7_Price = new javax.swing.JLabel();
        p7_Qty = new javax.swing.JSpinner();
        p7_AddToCart = new javax.swing.JButton();
        p8_Qty = new javax.swing.JSpinner();
        p8_AddToCart = new javax.swing.JButton();
        p8_Price = new javax.swing.JLabel();
        p9_Qty = new javax.swing.JSpinner();
        p9_Price = new javax.swing.JLabel();
        p9_AddToCart = new javax.swing.JButton();
        p2_CLatte = new javax.swing.JLabel();
        p3_HOCapuccino = new javax.swing.JLabel();
        p6_FBrownies = new javax.swing.JLabel();
        p9_MGTea = new javax.swing.JLabel();
        p8_SMilkshake = new javax.swing.JLabel();
        p5_CFCake = new javax.swing.JLabel();
        p4_BWaffle = new javax.swing.JLabel();
        p7_HChocolate = new javax.swing.JLabel();
        p1_Espresso = new javax.swing.JLabel();
        javax.swing.JLabel p2_Image = new javax.swing.JLabel();
        javax.swing.JLabel p1_Image = new javax.swing.JLabel();
        javax.swing.JLabel p3_Image = new javax.swing.JLabel();
        javax.swing.JLabel p9_Image = new javax.swing.JLabel();
        javax.swing.JLabel p8_Image = new javax.swing.JLabel();
        javax.swing.JLabel p7_Image = new javax.swing.JLabel();
        javax.swing.JLabel p4_Image = new javax.swing.JLabel();
        javax.swing.JLabel p5_Image = new javax.swing.JLabel();
        javax.swing.JLabel p6_Image = new javax.swing.JLabel();
        javax.swing.JLabel lblMenu = new javax.swing.JLabel();
        javax.swing.JButton btnLogout = new javax.swing.JButton();
        javax.swing.JLabel wdwBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Brewed & Blended");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAll.setBackground(new java.awt.Color(229, 195, 183));
        pnlAll.setMaximumSize(new java.awt.Dimension(1359, 750));
        pnlAll.setMinimumSize(new java.awt.Dimension(1359, 750));
        pnlAll.setPreferredSize(new java.awt.Dimension(1359, 750));
        pnlAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeft.setBackground(new java.awt.Color(219, 173, 157));
        pnlLeft.setOpaque(false);
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menuLogo.png"))); // NOI18N
        pnlLeft.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 39, -1, -1));

        lblCart.setBackground(new java.awt.Color(255, 255, 255));
        lblCart.setFont(new java.awt.Font("Hug Me Tight", 0, 24)); // NOI18N
        lblCart.setForeground(new java.awt.Color(127, 81, 89));
        lblCart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCart.setText("- cart -");
        pnlLeft.add(lblCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 150, 178, -1));

        tblCart.setAutoCreateRowSorter(true);
        tblCart.setBackground(new java.awt.Color(219, 173, 157));
        tblCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblCart.setForeground(new java.awt.Color(255, 255, 255));
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QTY", "Product", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCart.setFocusable(false);
        tblCart.setGridColor(new java.awt.Color(255, 255, 255));
        tblCart.setInheritsPopupMenu(true);
        tblCart.setRowHeight(25);
        tblCart.setSelectionBackground(new java.awt.Color(127, 81, 89));
        tblCart.setShowGrid(true);
        scrlCart.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setResizable(false);
            tblCart.getColumnModel().getColumn(1).setResizable(false);
            tblCart.getColumnModel().getColumn(2).setResizable(false);
        }

        pnlLeft.add(scrlCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 185, 362, 180));

        btnDelete.setBackground(new java.awt.Color(244, 227, 214));
        btnDelete.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(127, 81, 89));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Deletes a selected row in the Cart.");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusCycleRoot(true);
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 102, 40));

        btnClear.setBackground(new java.awt.Color(244, 227, 214));
        btnClear.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(127, 81, 89));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setToolTipText("Clears the Cart, the Receipt, and the Receipt textfile.");
        btnClear.setBorder(null);
        btnClear.setBorderPainted(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setFocusCycleRoot(true);
        btnClear.setFocusPainted(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlLeft.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 102, 40));

        btnBuy.setBackground(new java.awt.Color(244, 227, 214));
        btnBuy.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(127, 81, 89));
        btnBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buy.png"))); // NOI18N
        btnBuy.setText("Buy");
        btnBuy.setToolTipText("Finalizes the item/s in the Cart.");
        btnBuy.setBorder(null);
        btnBuy.setBorderPainted(false);
        btnBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuy.setFocusCycleRoot(true);
        btnBuy.setFocusPainted(false);
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        pnlLeft.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 102, 40));

        lblReceipt.setBackground(new java.awt.Color(255, 255, 255));
        lblReceipt.setFont(new java.awt.Font("Hug Me Tight", 0, 24)); // NOI18N
        lblReceipt.setForeground(new java.awt.Color(127, 81, 89));
        lblReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReceipt.setText("- Receipt -");
        pnlLeft.add(lblReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 178, -1));

        scrlReceipt.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        areaReceipt.setEditable(false);
        areaReceipt.setColumns(20);
        areaReceipt.setRows(5);
        areaReceipt.setFocusable(false);
        scrlReceipt.setViewportView(areaReceipt);

        pnlLeft.add(scrlReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 460, 362, 160));

        btnAdmin.setBackground(new java.awt.Color(244, 227, 214));
        btnAdmin.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(127, 81, 89));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/shop.png"))); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setToolTipText("Directs to the Shop.");
        btnAdmin.setBorder(null);
        btnAdmin.setBorderPainted(false);
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setFocusCycleRoot(true);
        btnAdmin.setFocusPainted(false);
        btnAdmin.setMaximumSize(new java.awt.Dimension(49, 17));
        btnAdmin.setMinimumSize(new java.awt.Dimension(49, 17));
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        pnlLeft.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 110, 40));

        btnPrint.setBackground(new java.awt.Color(244, 227, 214));
        btnPrint.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(127, 81, 89));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setToolTipText("Prints the Receipt.");
        btnPrint.setBorder(null);
        btnPrint.setBorderPainted(false);
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.setFocusCycleRoot(true);
        btnPrint.setFocusPainted(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        pnlLeft.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 102, 40));

        areaTotalPrice.setEditable(false);
        areaTotalPrice.setBackground(new java.awt.Color(255, 255, 255));
        areaTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        areaTotalPrice.setForeground(new java.awt.Color(127, 81, 89));
        areaTotalPrice.setText("₱");
        areaTotalPrice.setFocusable(false);
        pnlLeft.add(areaTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 150, 108, -1));

        btnExit.setBackground(new java.awt.Color(244, 227, 214));
        btnExit.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(127, 81, 89));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setToolTipText("Exits the Shop.");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusCycleRoot(true);
        btnExit.setFocusPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlLeft.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 102, 40));

        pnlAll.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 760));

        pnlRight.setBackground(new java.awt.Color(219, 173, 157));
        pnlRight.setOpaque(false);
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(219, 173, 157));
        pnlMenu.setOpaque(false);
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDessert.setFont(new java.awt.Font("Hug Me Tight", 1, 24)); // NOI18N
        lblDessert.setForeground(new java.awt.Color(128, 80, 71));
        lblDessert.setText("Dessert");
        pnlMenu.add(lblDessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        lblCoffee.setFont(new java.awt.Font("Hug Me Tight", 1, 24)); // NOI18N
        lblCoffee.setForeground(new java.awt.Color(128, 80, 71));
        lblCoffee.setText("Coffee");
        pnlMenu.add(lblCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblNoncoffee.setFont(new java.awt.Font("Hug Me Tight", 1, 24)); // NOI18N
        lblNoncoffee.setForeground(new java.awt.Color(128, 80, 71));
        lblNoncoffee.setText("Non-coffee");
        pnlMenu.add(lblNoncoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        p2_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p2_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p2_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p2_AddToCart.setText("+");
        p2_AddToCart.setToolTipText("Adds item to Cart.");
        p2_AddToCart.setBorder(null);
        p2_AddToCart.setBorderPainted(false);
        p2_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p2_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 36, 30));

        p2_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p2_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p2_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 109, -1));

        p2_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p2_Price.setForeground(new java.awt.Color(192, 108, 52));
        p2_Price.setText("₱");
        pnlMenu.add(p2_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 28));

        p3_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p3_Price.setForeground(new java.awt.Color(192, 108, 52));
        p3_Price.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p3_Price.setText("₱");
        pnlMenu.add(p3_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 150, 28));

        p3_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p3_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p3_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 109, -1));

        p3_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p3_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p3_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p3_AddToCart.setText("+");
        p3_AddToCart.setToolTipText("Adds item to Cart.");
        p3_AddToCart.setBorder(null);
        p3_AddToCart.setBorderPainted(false);
        p3_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p3_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 36, 30));

        p1_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p1_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p1_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 109, -1));

        p1_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p1_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p1_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p1_AddToCart.setText("+");
        p1_AddToCart.setToolTipText("Adds item to Cart.");
        p1_AddToCart.setBorder(null);
        p1_AddToCart.setBorderPainted(false);
        p1_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p1_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 36, 30));

        p1_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p1_Price.setForeground(new java.awt.Color(192, 108, 52));
        p1_Price.setText("₱");
        pnlMenu.add(p1_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 89, 28));

        p4_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p4_Price.setForeground(new java.awt.Color(192, 108, 52));
        p4_Price.setText("₱");
        pnlMenu.add(p4_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 151, 28));

        p4_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p4_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p4_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 109, -1));

        p4_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p4_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p4_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p4_AddToCart.setText("+");
        p4_AddToCart.setToolTipText("Adds item to Cart.");
        p4_AddToCart.setBorder(null);
        p4_AddToCart.setBorderPainted(false);
        p4_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p4_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 36, 30));

        p5_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p5_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p5_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 109, -1));

        p5_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p5_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p5_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p5_AddToCart.setText("+");
        p5_AddToCart.setToolTipText("Adds item to Cart.");
        p5_AddToCart.setBorder(null);
        p5_AddToCart.setBorderPainted(false);
        p5_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p5_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 36, 30));

        p5_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p5_Price.setForeground(new java.awt.Color(192, 108, 52));
        p5_Price.setText("₱");
        pnlMenu.add(p5_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 151, 28));

        p6_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p6_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p6_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 109, -1));

        p6_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p6_Price.setForeground(new java.awt.Color(192, 108, 52));
        p6_Price.setText("₱");
        pnlMenu.add(p6_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 151, 28));

        p6_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p6_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p6_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p6_AddToCart.setText("+");
        p6_AddToCart.setToolTipText("Adds item to Cart.");
        p6_AddToCart.setBorder(null);
        p6_AddToCart.setBorderPainted(false);
        p6_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p6_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 36, 30));

        p7_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p7_Price.setForeground(new java.awt.Color(192, 108, 52));
        p7_Price.setText("₱");
        pnlMenu.add(p7_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 151, 28));

        p7_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p7_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p7_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 109, -1));

        p7_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p7_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p7_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p7_AddToCart.setText("+");
        p7_AddToCart.setToolTipText("Adds item to Cart.");
        p7_AddToCart.setBorder(null);
        p7_AddToCart.setBorderPainted(false);
        p7_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p7_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 36, 30));

        p8_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p8_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p8_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 109, -1));

        p8_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p8_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p8_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p8_AddToCart.setText("+");
        p8_AddToCart.setToolTipText("Adds item to Cart.");
        p8_AddToCart.setBorder(null);
        p8_AddToCart.setBorderPainted(false);
        p8_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p8_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 36, 30));

        p8_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p8_Price.setForeground(new java.awt.Color(192, 108, 52));
        p8_Price.setText("₱");
        pnlMenu.add(p8_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 151, 28));

        p9_Qty.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p9_Qty.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        pnlMenu.add(p9_Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 109, -1));

        p9_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p9_Price.setForeground(new java.awt.Color(192, 108, 52));
        p9_Price.setText("₱");
        pnlMenu.add(p9_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 151, 28));

        p9_AddToCart.setBackground(new java.awt.Color(161, 96, 84));
        p9_AddToCart.setFont(new java.awt.Font("Hug Me Tight", 0, 18)); // NOI18N
        p9_AddToCart.setForeground(new java.awt.Color(255, 255, 255));
        p9_AddToCart.setText("+");
        p9_AddToCart.setToolTipText("Adds item to Cart.");
        p9_AddToCart.setBorder(null);
        p9_AddToCart.setBorderPainted(false);
        p9_AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p9_AddToCartActionPerformed(evt);
            }
        });
        pnlMenu.add(p9_AddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 36, 30));

        p2_CLatte.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p2_CLatte.setForeground(new java.awt.Color(128, 80, 71));
        p2_CLatte.setText("Caramel Latte");
        pnlMenu.add(p2_CLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 120, 28));

        p3_HOCapuccino.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p3_HOCapuccino.setForeground(new java.awt.Color(128, 80, 71));
        p3_HOCapuccino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p3_HOCapuccino.setText("Hot Oat Capuccino");
        pnlMenu.add(p3_HOCapuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 150, 28));

        p6_FBrownies.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p6_FBrownies.setForeground(new java.awt.Color(128, 80, 71));
        p6_FBrownies.setText("Fudgy Brownies");
        pnlMenu.add(p6_FBrownies, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 151, 28));

        p9_MGTea.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p9_MGTea.setForeground(new java.awt.Color(128, 80, 71));
        p9_MGTea.setText("Matcha Green Tea");
        pnlMenu.add(p9_MGTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 151, 28));

        p8_SMilkshake.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p8_SMilkshake.setForeground(new java.awt.Color(128, 80, 71));
        p8_SMilkshake.setText("Strawberry Milkshake");
        pnlMenu.add(p8_SMilkshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 170, 28));

        p5_CFCake.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p5_CFCake.setForeground(new java.awt.Color(128, 80, 71));
        p5_CFCake.setText("Chocolate Fudge Cake");
        pnlMenu.add(p5_CFCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 180, 28));

        p4_BWaffle.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p4_BWaffle.setForeground(new java.awt.Color(128, 80, 71));
        p4_BWaffle.setText("Belgian Waffle");
        pnlMenu.add(p4_BWaffle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 151, 28));

        p7_HChocolate.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p7_HChocolate.setForeground(new java.awt.Color(128, 80, 71));
        p7_HChocolate.setText("Hot Chocolate");
        pnlMenu.add(p7_HChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 151, 28));

        p1_Espresso.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        p1_Espresso.setForeground(new java.awt.Color(128, 80, 71));
        p1_Espresso.setText("Espresso ");
        pnlMenu.add(p1_Espresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 170, 28));

        p2_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p2.png"))); // NOI18N
        pnlMenu.add(p2_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, 80));

        p1_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p1.png"))); // NOI18N
        pnlMenu.add(p1_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 56, 150, 70));

        p3_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p3_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p3.png"))); // NOI18N
        pnlMenu.add(p3_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 150, 80));

        p9_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p9_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p9.png"))); // NOI18N
        pnlMenu.add(p9_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 383, 150, -1));

        p8_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p8_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p8.png"))); // NOI18N
        pnlMenu.add(p8_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 150, 90));

        p7_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p7_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p7.png"))); // NOI18N
        pnlMenu.add(p7_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 150, 80));

        p4_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p4_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p4.png"))); // NOI18N
        pnlMenu.add(p4_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, 70));

        p5_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p5.png"))); // NOI18N
        pnlMenu.add(p5_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 150, 80));

        p6_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p6_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/p6.png"))); // NOI18N
        pnlMenu.add(p6_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 150, 80));

        pnlRight.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 818, -1));

        lblMenu.setBackground(new java.awt.Color(255, 255, 255));
        lblMenu.setFont(new java.awt.Font("Hug Me Tight", 0, 44)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(244, 227, 214));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("- Menu -");
        pnlRight.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 230, -1));

        btnLogout.setBackground(new java.awt.Color(244, 227, 214));
        btnLogout.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(127, 81, 89));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setToolTipText("Exits the Shop.");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusCycleRoot(true);
        btnLogout.setFocusPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlRight.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 120, 40));

        pnlAll.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 830, 770));

        wdwBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menuBg.png"))); // NOI18N
        wdwBg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(wdwBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // If recipt area is empty, show error; else, try to print receipt
        if (areaReceipt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"You have no receipt yet! \nPlease add item/s to Cart and click Buy.","No Receipt",JOptionPane.ERROR_MESSAGE);
        } else {
            try{
            areaReceipt.print();
            } catch (PrinterException e){
                System.out.print("Print Fail");
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // If Cart table is empty, show error; else, calculate order and print receipt
        if (tblCart.getRowCount() == 0){
            JOptionPane.showMessageDialog(this,"You have no item/s on your cart! \nPlease add product/s from the Menu on the right.","No Items on Cart",JOptionPane.ERROR_MESSAGE);
        } 
        else if (JOptionPane.showConfirmDialog(null, "Are you certain of your purchase? This action cannot be undone.", "Finalize Order?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            areaReceipt.setText("=============================================\n");
            areaReceipt.setText(areaReceipt.getText()+"\t"+"-+ BREWED & BLENDED +-\n");
            areaReceipt.setText(areaReceipt.getText()+"=============================================\n");

            //Instantiate total items sold and total price
            int qtyTotal = 0;
            int qty;
            double priceTotal = 0;
            double price;

            //List down purchased items in Cart
            DefaultTableModel model = (DefaultTableModel)tblCart.getModel();
            areaReceipt.setText(areaReceipt.getText()+"QTY"+"\t"+"PRODUCT NAME"+"           \t"+"PRICE\n");
            for(int i = 0; i<tblCart.getRowCount(); i++){
                String productQty = tblCart.getValueAt(i,0).toString();
                String productName = tblCart.getValueAt(i,1).toString();
                String totalAmount = tblCart.getValueAt(i,2).toString();

                qty = Integer.parseInt(productQty);
                qtyTotal += qty; 
                price = Double.parseDouble(totalAmount);
                priceTotal += price; 
                areaReceipt.setText(areaReceipt.getText()+productQty+"\t"+productName+"   \t"+totalAmount+"\n");
                areaTotalPrice.setText("₱" + Double.toString(priceTotal));
                
                //Save to orders in the database
                saveOrderToDatabase(productName, productQty, totalAmount);
            }
            printReceiptDetails(Integer.toString(qtyTotal), Double.toString(priceTotal));
            writeToFile();
            JOptionPane.showMessageDialog(this,"Please present your receipt to the Brewed and Blended Cafe\n"
                    + " in Camachilli St, Corner Acacia in Matina within day of purchase!","Order Completed!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // If Cart table is empty, show error; else, clear out the Cart table
        if (tblCart.getRowCount() == 0){
            JOptionPane.showMessageDialog(this,"You have no item/s in your cart! \nPlease add item/s from the Menu.","No Item/s in Cart",JOptionPane.ERROR_MESSAGE);
        }
        else if (JOptionPane.showConfirmDialog(null, "Are you sure you want to clear your Cart? This action cannot be undone.", 
                "Clear Cart?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // Clear the Receipt
            areaReceipt.setText("");
            // Clear the Cart
            DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
            model.setRowCount(0);
            // Clear the Total Price
            areaTotalPrice.setText("");
            // Clear the textfile
            File receipt = new File("receipt.txt");
            FileWriter writer;
            try {
                //Clear receipt textfile
                writer = new FileWriter(receipt);
                writer.write("");
            } catch (IOException ex) {
                Logger.getLogger(CafeMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblCart.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        
        // If Cart table is empty, show error; else if no row is selected, show error; else, delete selected row
        if (tblCart.getRowCount() == 0){
            JOptionPane.showMessageDialog(this,"You have no item/s in your cart! \nPlease add item/s from the Menu.","No Item/s in Cart",JOptionPane.ERROR_MESSAGE);
        }
        else if (row < 0) {
             JOptionPane.showMessageDialog(this,"Please select item from the table above.","No item selected!",JOptionPane.ERROR_MESSAGE);
        } 
        else if (JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected item? This action cannot be undone.", 
                "Delete Selected Item?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            while(row != -1) {
                int rowModelId = tblCart.convertRowIndexToModel(tblCart.getSelectedRow());
                model.removeRow(rowModelId);
                break;
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void p9_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p9_AddToCartActionPerformed
        getProductDetails(9);
    }//GEN-LAST:event_p9_AddToCartActionPerformed

    private void p8_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8_AddToCartActionPerformed
        getProductDetails(8);
    }//GEN-LAST:event_p8_AddToCartActionPerformed

    private void p7_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7_AddToCartActionPerformed
        getProductDetails(7);
    }//GEN-LAST:event_p7_AddToCartActionPerformed

    private void p6_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6_AddToCartActionPerformed
        getProductDetails(6);
    }//GEN-LAST:event_p6_AddToCartActionPerformed

    private void p5_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5_AddToCartActionPerformed
        getProductDetails(5);
    }//GEN-LAST:event_p5_AddToCartActionPerformed

    private void p4_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4_AddToCartActionPerformed
        getProductDetails(4);
    }//GEN-LAST:event_p4_AddToCartActionPerformed

    private void p1_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1_AddToCartActionPerformed
        getProductDetails(1);
    }//GEN-LAST:event_p1_AddToCartActionPerformed

    private void p3_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3_AddToCartActionPerformed
        getProductDetails(3);
    }//GEN-LAST:event_p3_AddToCartActionPerformed

    private void p2_AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2_AddToCartActionPerformed
        getProductDetails(2);
    }//GEN-LAST:event_p2_AddToCartActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Shop?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            closeWindow();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Exit Shop?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            closeWindow();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Exit Shop?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new CafeLogin().setVisible(true);
            closeWindow();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Go to Admin?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new CafeAdmin().setVisible(true);
            closeWindow();
        }
    }//GEN-LAST:event_btnAdminActionPerformed

    private void designComponents() {
        // Cart design
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer)tblCart.getDefaultRenderer(Object.class);
        renderer.setHorizontalAlignment( SwingConstants.CENTER );
        tblCart.getTableHeader().setOpaque(false);
        tblCart.getTableHeader().setForeground(new Color(127,81,89));
        tblCart.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD , 14));
        tblCart.getColumnModel().getColumn(0).setMaxWidth(50);
        tblCart.getColumnModel().getColumn(1).setMaxWidth(350);
        tblCart.getColumnModel().getColumn(2).setMaxWidth(100);
        
        // If admin is logged in, show 'Admin' button; else, hide 'Admin' buttt
        String username = new UserRecord().getUsername();
        if (username.equalsIgnoreCase("admin"))
            btnAdmin.setVisible(true);
        else 
            btnAdmin.setVisible(false);
    }
    
    private void matchMenuToDatabase() {
        try { 
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
            String user = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();

            // Arrays for component references
            JLabel[] nameLabels = {p1_Espresso, p2_CLatte, p3_HOCapuccino, p4_BWaffle, p5_CFCake, p6_FBrownies, p7_HChocolate, p8_SMilkshake, p9_MGTea};
            JLabel[] priceLabels = {p1_Price, p2_Price, p3_Price, p4_Price, p5_Price, p6_Price, p7_Price, p8_Price, p9_Price};
            JButton[] addButtons = {p1_AddToCart, p2_AddToCart, p3_AddToCart, p4_AddToCart, p5_AddToCart, p6_AddToCart, p7_AddToCart, p8_AddToCart, p9_AddToCart};
            JSpinner[] qtySpinners = {p1_Qty, p2_Qty, p3_Qty, p4_Qty, p5_Qty, p6_Qty, p7_Qty, p8_Qty, p9_Qty};

            for (int i = 1; i <= 9; i++) {
                String query = "SELECT ProductName, Price, InStock FROM products WHERE ProductId=" + i;
                ResultSet rs = st.executeQuery(query);

                if (rs.next()) {
                    // Set product name
                    String productName = rs.getString("ProductName");
                    nameLabels[i - 1].setText(productName);

                    // Set product price or mark as "Out of Stock"
                    int stock = rs.getInt("InStock");
                    if (stock == 0) {
                        priceLabels[i - 1].setText("Out of Stock");
                        addButtons[i - 1].setEnabled(false);
                        qtySpinners[i - 1].setEnabled(false);
                    } else {
                        String price = "₱" + rs.getInt("Price");
                        priceLabels[i - 1].setText(price);
                        addButtons[i - 1].setEnabled(true);
                        qtySpinners[i - 1].setEnabled(true);
                    }
                } else {
                    System.out.println("Error retrieving product with ID " + i);
                }
            }
            System.out.println("Menu items successfully matched to database!");
            con.close();
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    
    private int getProductDetails(int n) {
        // Arrays for component references
        JSpinner[] qtySpinners = {p1_Qty, p2_Qty, p3_Qty, p4_Qty, p5_Qty, p6_Qty, p7_Qty, p8_Qty, p9_Qty};
        JLabel[] nameLabels = {p1_Espresso, p2_CLatte, p3_HOCapuccino, p4_BWaffle, p5_CFCake, p6_FBrownies, p7_HChocolate, p8_SMilkshake, p9_MGTea};
        JLabel[] priceLabels = {p1_Price, p2_Price, p3_Price, p4_Price, p5_Price, p6_Price, p7_Price, p8_Price, p9_Price};

        // Ensure index n is valid (1-9)
        if (n < 1 || n > 9) {
            throw new IllegalArgumentException("Invalid product index: " + n);
        }
        // Get the components based on the index 
        JSpinner spnrQty = qtySpinners[n - 1];
        JLabel lblName = nameLabels[n - 1];
        JLabel lblPrice = priceLabels[n - 1];

        // Get product details and pass it to addToCart method
        int productQty = (int) spnrQty.getValue();
        if (productQty == 0) {
            JOptionPane.showMessageDialog(this, "Please select amount to buy.", "No quantity specified!", JOptionPane.ERROR_MESSAGE);
        } else {
            String productName = lblName.getText();
            double productPrice = Double.parseDouble(lblPrice.getText().substring(1)) * productQty;
            addToCart(productQty, productName, productPrice);
        }
        return 0;
    }

    private void addToCart(int productQty, String productName, double productPrice) {
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        
        // If Cart table is empty, show error; else, clear out the Cart table
        if (model.getRowCount() == 0){
            model.addRow(new Object[] {productQty, productName, productPrice});
        } else {
            //Check if item is already in Cart
            for(int r = 0; r < model.getRowCount();r++){
                // If it is, remove it then add again with new product details; else, add product to Cart
                if (productName.equals(model.getValueAt(r, 1))){
                    model.removeRow(r);
                    model.addRow(new Object[] {productQty, productName, productPrice});
                    break;
                } else if (r == (model.getRowCount()-1)){
                    model.addRow(new Object[] {productQty, productName, productPrice});
                    break;
                }
            }
        }
    }
    
    private String getDate(){ 
        // Get the date and time and format it for the OrderDate
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        return date;
    }
    
    private String getFileDate(){ 
        // Get the date and time and format it for the receipt textfile filename
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        return date;
    }
    
    private void saveOrderToDatabase(String productName, String productQty, String totalAmount){
        try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();
                String query;
                
                // Retrieve ProductId from the database
                query = "SELECT ProductId FROM products WHERE ProductName='"+productName+"';";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()){
                    String productId = String.valueOf(rs.getInt("ProductId"));
                    // Retrieve username
                    String username = new UserRecord().getUsername();
                    // Retrieve UserId of the matching username from the database
                    query = "SELECT UserId FROM users WHERE Username='"+username+"';";
                    rs = st.executeQuery(query);
                    if (rs.next()){
                        String userId = String.valueOf(rs.getInt("UserId"));
                        
                        query = "INSERT INTO orders (UserId, ProductId, Quantity, TotalAmount, OrderDate) VALUES "
                                + "("+userId+", "+productId+", "+productQty+", "+totalAmount+", '"+getDate()+"');";
                        st.executeUpdate(query);
                    }
                } else{
                    System.out.println("Error saving order to database.");
                }
                con.close();
            } catch (HeadlessException | ClassNotFoundException | SQLException e){
                    System.out.println("Error " + e.getMessage());
            }
    }
    
    private void printReceiptDetails(String qtyTotal, String priceTotal) {
        // Get the username
        String username = new UserRecord().getUsername();
        // Format receipt with the total quantity, price, date, and username
        String receiptText = String.format(
            "\n\nQTY SOLD\t\t        GROSS AMOUNT\n" +
            "%s Item/s Sold\t\t        %s\n" +
            "=============================================\n" +
            "Transaction Date: %s\n" +
            "=============================================\n" +
            "Brewed & Blended Co.\n" +
            "Camachilli St, Corner Acacia, Matina\n" +
            "+63 908 818 4444\n\n" +
            "Present receipt within day of purchase!\n" +
            "Thank you %s! Please come again!",
            qtyTotal, priceTotal, getDate(), username
        );
        areaReceipt.setText(areaReceipt.getText() + receiptText);
    }
    
    private void writeToFile(){
        // Create new receipt file with the order date and time
        File receipt = new File("Receipt_" + getFileDate() + ".txt");
        FileWriter writer;
            try {
                //Clear receipt textfile
                writer = new FileWriter(receipt);
                writer.write("");
                //Write text of 'areaReceipt' into the receipt textfile
                writer = new FileWriter(receipt.getAbsoluteFile(), true);
                areaReceipt.write(writer);
                writer.flush();
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(CafeMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CafeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //FlatLightLaf.registerCustomDefaultsSource("style");
        //FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CafeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaReceipt;
    private javax.swing.JTextField areaTotalPrice;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton p1_AddToCart;
    private javax.swing.JLabel p1_Espresso;
    private javax.swing.JLabel p1_Price;
    private javax.swing.JSpinner p1_Qty;
    private javax.swing.JButton p2_AddToCart;
    private javax.swing.JLabel p2_CLatte;
    private javax.swing.JLabel p2_Price;
    private javax.swing.JSpinner p2_Qty;
    private javax.swing.JButton p3_AddToCart;
    private javax.swing.JLabel p3_HOCapuccino;
    private javax.swing.JLabel p3_Price;
    private javax.swing.JSpinner p3_Qty;
    private javax.swing.JButton p4_AddToCart;
    private javax.swing.JLabel p4_BWaffle;
    private javax.swing.JLabel p4_Price;
    private javax.swing.JSpinner p4_Qty;
    private javax.swing.JButton p5_AddToCart;
    private javax.swing.JLabel p5_CFCake;
    private javax.swing.JLabel p5_Price;
    private javax.swing.JSpinner p5_Qty;
    private javax.swing.JButton p6_AddToCart;
    private javax.swing.JLabel p6_FBrownies;
    private javax.swing.JLabel p6_Price;
    private javax.swing.JSpinner p6_Qty;
    private javax.swing.JButton p7_AddToCart;
    private javax.swing.JLabel p7_HChocolate;
    private javax.swing.JLabel p7_Price;
    private javax.swing.JSpinner p7_Qty;
    private javax.swing.JButton p8_AddToCart;
    private javax.swing.JLabel p8_Price;
    private javax.swing.JSpinner p8_Qty;
    private javax.swing.JLabel p8_SMilkshake;
    private javax.swing.JButton p9_AddToCart;
    private javax.swing.JLabel p9_MGTea;
    private javax.swing.JLabel p9_Price;
    private javax.swing.JSpinner p9_Qty;
    javax.swing.JPanel pnlAll;
    private javax.swing.JScrollPane scrlCart;
    private javax.swing.JScrollPane scrlReceipt;
    private javax.swing.JTable tblCart;
    // End of variables declaration//GEN-END:variables
}
