package menus;

import java.awt.HeadlessException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class CafeLogin extends CafeWindow {

    /**
     * Creates new form CafeWelcome
     */
    public CafeLogin() {
        initComponents();
        displayWindow();
    }
   
    @Override
    public void displayWindow() {
        initializeWindow(this);
        setVisible(true);
    }

    @Override
    public void closeWindow() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel pnlAll = new javax.swing.JPanel();
        javax.swing.JLabel lblContact2 = new javax.swing.JLabel();
        javax.swing.JLabel lblContact3 = new javax.swing.JLabel();
        javax.swing.JLabel lblContact4 = new javax.swing.JLabel();
        javax.swing.JLabel lblContact1 = new javax.swing.JLabel();
        javax.swing.JButton btnRegister = new javax.swing.JButton();
        javax.swing.JLabel lblLogin = new javax.swing.JLabel();
        javax.swing.JLabel lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        javax.swing.JLabel lblPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btnPeek = new javax.swing.JButton();
        javax.swing.JButton btnLogin = new javax.swing.JButton();
        javax.swing.JLabel sideImage = new javax.swing.JLabel();
        javax.swing.JLabel welcomeLogo = new javax.swing.JLabel();
        javax.swing.JLabel welcomeBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brewed & Blended");
        setMinimumSize(new java.awt.Dimension(750, 480));
        setName(""); // NOI18N
        setResizable(false);

        pnlAll.setBackground(new java.awt.Color(244, 227, 214));
        pnlAll.setMaximumSize(new java.awt.Dimension(750, 500));
        pnlAll.setMinimumSize(new java.awt.Dimension(750, 500));
        pnlAll.setName(""); // NOI18N
        pnlAll.setPreferredSize(new java.awt.Dimension(750, 500));
        pnlAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContact2.setForeground(new java.awt.Color(244, 227, 214));
        lblContact2.setText("09088184444");
        pnlAll.add(lblContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 200, 20));

        lblContact3.setForeground(new java.awt.Color(244, 227, 214));
        lblContact3.setText("Juna Subdivision, Camachilli St.,");
        pnlAll.add(lblContact3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 30));

        lblContact4.setForeground(new java.awt.Color(244, 227, 214));
        lblContact4.setText("Corner Acacia, Matina, Davao City");
        pnlAll.add(lblContact4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 20));

        lblContact1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContact1.setForeground(new java.awt.Color(244, 227, 214));
        lblContact1.setText("Contact Us:");
        pnlAll.add(lblContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 60));

        btnRegister.setBackground(new java.awt.Color(127, 81, 89));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(127, 81, 89));
        btnRegister.setText("Register");
        btnRegister.setToolTipText("A new user? Click me.");
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        pnlAll.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 120, 40));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(127, 81, 89));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogin.setText("Don't have an account?");
        lblLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 170, 30));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(127, 81, 89));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username");
        lblUsername.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 110, 30));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 280, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(127, 81, 89));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password");
        lblPassword.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 110, 30));

        tfPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 280, 30));

        btnPeek.setBackground(new java.awt.Color(244, 227, 214));
        btnPeek.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnPeek.setForeground(new java.awt.Color(127, 81, 89));
        btnPeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/peek.png"))); // NOI18N
        btnPeek.setToolTipText("Show Password");
        btnPeek.setBorderPainted(false);
        btnPeek.setContentAreaFilled(false);
        btnPeek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeek.setRequestFocusEnabled(false);
        btnPeek.setRolloverEnabled(false);
        btnPeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPeekMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPeekMouseReleased(evt);
            }
        });
        pnlAll.add(btnPeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 30, 30));

        btnLogin.setBackground(new java.awt.Color(127, 81, 89));
        btnLogin.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(244, 227, 214));
        btnLogin.setText("Login");
        btnLogin.setToolTipText("");
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlAll.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 160, 40));

        sideImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/loginImg.png"))); // NOI18N
        sideImage.setText("sideImage");
        pnlAll.add(sideImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        welcomeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        pnlAll.add(welcomeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 370, 120));

        welcomeBg.setBackground(new java.awt.Color(244, 227, 214));
        welcomeBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/loginBg.png"))); // NOI18N
        welcomeBg.setName(""); // NOI18N
        pnlAll.add(welcomeBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // If either username or password textfields are empty, show error
        if (tfUsername.getText().isEmpty() || tfPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in the details to login.","No Login Info",JOptionPane.ERROR_MESSAGE);
        }
        else {
            try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();
                
                String username = tfUsername.getText();
                String password = hashPassword(tfPassword.getText()); // Hash entered password to match with hashed password in the database
                String query;
                
                // Check if entered username and password matches with data in database; if yes, login; if no, show error
                query = "SELECT * FROM users WHERE Username='"+username+"' AND Password='"+password+"';";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()){
                    JOptionPane.showMessageDialog(this,"Welcome back, " + username + "!","Successfully logged in!",JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("Successfully logged in!");
                    
                    // Save username
                    new UserRecord().setUsername(username);
                    
                    // If admin is logging in
                    if ("admin".equals(username)){
                        new CafeAdmin().setVisible(true);
                        this.dispose();
                    } else {
                        new CafeMenu().setVisible(true);
                        this.dispose();
                    }
                } else{
                    JOptionPane.showMessageDialog(this,"Incorrect Username or Password. Please try again.","Invalid Login Details",JOptionPane.ERROR_MESSAGE);
                }
                con.close();
                
            } catch (HeadlessException | ClassNotFoundException | SQLException e){
                System.out.println("Error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnPeekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeekMousePressed
        tfPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnPeekMousePressed

    private void btnPeekMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeekMouseReleased
        tfPassword.setEchoChar('*');
    }//GEN-LAST:event_btnPeekMouseReleased

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Proceed to Register?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new CafeRegister().setVisible(true);
            closeWindow();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed
    
    public String hashPassword(String password) {
        try {
            MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = messageDigest.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Error: Could not hash password", e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CafeLogin().setVisible(true);
                System.out.print("Reached this Run");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPeek;
    public javax.swing.JPasswordField tfPassword;
    public javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
