package menus;

import java.awt.HeadlessException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class CafeRegister extends CafeWindow {

    /**
     * Creates new form CafeWelcome
     */
    public CafeRegister() {
        initComponents();
        displayWindow();
    }
    
    @Override
    public void displayWindow() {
        initializeWindow(this);
        setVisible(true);
    }

    @Override
    public void closeWindow() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel pnlAll = new javax.swing.JPanel();
        javax.swing.JLabel lblContact2 = new javax.swing.JLabel();
        javax.swing.JLabel lblContact3 = new javax.swing.JLabel();
        javax.swing.JLabel lblContact4 = new javax.swing.JLabel();
        javax.swing.JLabel lblContact1 = new javax.swing.JLabel();
        javax.swing.JLabel lblFirstName = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        javax.swing.JLabel lblLastName = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        javax.swing.JLabel lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        javax.swing.JLabel lblContactNo = new javax.swing.JLabel();
        tfContactNo = new javax.swing.JTextField();
        javax.swing.JLabel lblEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        javax.swing.JLabel lblPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btnPeek = new javax.swing.JButton();
        javax.swing.JButton btnRegister = new javax.swing.JButton();
        javax.swing.JButton btnLogin = new javax.swing.JButton();
        javax.swing.JLabel lblLogin = new javax.swing.JLabel();
        javax.swing.JLabel sideImage = new javax.swing.JLabel();
        javax.swing.JLabel welcomeLogo = new javax.swing.JLabel();
        javax.swing.JLabel welcomeBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brewed & Blended");
        setMinimumSize(new java.awt.Dimension(770, 620));
        setName(""); // NOI18N
        setResizable(false);

        pnlAll.setBackground(new java.awt.Color(244, 227, 214));
        pnlAll.setMaximumSize(new java.awt.Dimension(770, 590));
        pnlAll.setMinimumSize(new java.awt.Dimension(770, 590));
        pnlAll.setName(""); // NOI18N
        pnlAll.setPreferredSize(new java.awt.Dimension(770, 590));
        pnlAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContact2.setForeground(new java.awt.Color(244, 227, 214));
        lblContact2.setText("09088184444");
        pnlAll.add(lblContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 200, 20));

        lblContact3.setForeground(new java.awt.Color(244, 227, 214));
        lblContact3.setText("Juna Subdivision, Camachilli St.,");
        pnlAll.add(lblContact3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 200, 30));

        lblContact4.setForeground(new java.awt.Color(244, 227, 214));
        lblContact4.setText("Corner Acacia, Matina, Davao City");
        pnlAll.add(lblContact4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 200, 20));

        lblContact1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContact1.setForeground(new java.awt.Color(244, 227, 214));
        lblContact1.setText("Contact Us:");
        pnlAll.add(lblContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, 60));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(127, 81, 89));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFirstName.setText("First Name");
        lblFirstName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 110, 30));

        tfFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfFirstName.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 160, 30));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(127, 81, 89));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLastName.setText("Last Name");
        lblLastName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 110, 30));

        tfLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfLastName.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 150, 30));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(127, 81, 89));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username");
        lblUsername.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 110, 30));

        tfUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 160, 30));

        lblContactNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContactNo.setForeground(new java.awt.Color(127, 81, 89));
        lblContactNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContactNo.setText("Phone No. (11-digit)");
        lblContactNo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 190, 30));

        tfContactNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfContactNo.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 150, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(127, 81, 89));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail.setText("Email Address");
        lblEmail.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 110, 30));

        tfEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 320, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(127, 81, 89));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password");
        lblPassword.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 110, 30));

        tfPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(127, 81, 89));
        pnlAll.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 320, 30));

        btnPeek.setBackground(new java.awt.Color(244, 227, 214));
        btnPeek.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnPeek.setForeground(new java.awt.Color(127, 81, 89));
        btnPeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/peek.png"))); // NOI18N
        btnPeek.setToolTipText("Show Password");
        btnPeek.setBorderPainted(false);
        btnPeek.setContentAreaFilled(false);
        btnPeek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeek.setRequestFocusEnabled(false);
        btnPeek.setRolloverEnabled(false);
        btnPeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPeekMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPeekMouseReleased(evt);
            }
        });
        pnlAll.add(btnPeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 30, 30));

        btnRegister.setBackground(new java.awt.Color(127, 81, 89));
        btnRegister.setFont(new java.awt.Font("Hug Me Tight", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(244, 227, 214));
        btnRegister.setText("Register");
        btnRegister.setToolTipText("");
        btnRegister.setBorderPainted(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        pnlAll.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 200, 40));

        btnLogin.setBackground(new java.awt.Color(127, 81, 89));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(127, 81, 89));
        btnLogin.setText("Log in");
        btnLogin.setToolTipText("Already registered? Click me.");
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlAll.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 130, 40));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(127, 81, 89));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogin.setText("Already have an account?");
        lblLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlAll.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 200, 30));

        sideImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registerImg.png"))); // NOI18N
        sideImage.setMaximumSize(new java.awt.Dimension(330, 590));
        sideImage.setMinimumSize(new java.awt.Dimension(330, 590));
        sideImage.setPreferredSize(new java.awt.Dimension(330, 590));
        pnlAll.add(sideImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 590));

        welcomeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/programLogo.png"))); // NOI18N
        pnlAll.add(welcomeLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 370, 130));

        welcomeBg.setBackground(new java.awt.Color(244, 227, 214));
        welcomeBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registerBg.png"))); // NOI18N
        welcomeBg.setName(""); // NOI18N
        pnlAll.add(welcomeBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure?", "Proceed to Log In?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new CafeLogin().setVisible(true);
            closeWindow();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // If not all textfields are filled in, show error
        if (tfFirstName.getText().isEmpty() || tfLastName.getText().isEmpty() || tfUsername.getText().isEmpty() || tfContactNo.getText().isEmpty() || tfEmail.getText().isEmpty() || tfPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in the details to login.","No Login Info",JOptionPane.ERROR_MESSAGE);
        } // If entered contact number is not numbers or not equal to 11-digits
        else if (!tfContactNo.getText().matches("[0-9]+") || tfContactNo.getText().length() != 11){
            JOptionPane.showMessageDialog(this,"Please enter a valid 11-digit phone number.","Invalid Phone Number",JOptionPane.ERROR_MESSAGE);
        } 
        else {
            try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = "jdbc:MySQL://localhost:3306/brewedblended_db";
                String user = "root";
                String pass = "";
                Connection con = DriverManager.getConnection(url,user,pass);
                Statement st = con.createStatement();
                
                String firstName = tfFirstName.getText();
                String lastName = tfLastName.getText();
                String username = tfUsername.getText();
                String contactNo = tfContactNo.getText();
                String email = tfEmail.getText();
                String password = hashPassword(tfPassword.getText()); // Hash password for security
                String query;
                
                // Check if entered username or email is already registered; if yes, show error; if no, write user details to database
                query = "SELECT * FROM users WHERE Username='"+username+"' OR Email='"+email+"';";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()){
                    JOptionPane.showMessageDialog(this,"Sorry, the username or email you entered is already used. \nPlease try another one.",
                            "Account Already Exists",JOptionPane.ERROR_MESSAGE);
                } else{
                    query = "INSERT INTO users (FirstName, LastName, Username, ContactNo, Email, Password) "
                        + "VALUES ('"+firstName+"', '"+lastName+"', '"+username+"', '"+contactNo+"', '"+email+"', '"+password+"');";
                    st.executeUpdate(query);
                    JOptionPane.showMessageDialog(this,"Hello, " + username + "!","Successfully registered!",JOptionPane.OK_OPTION);
                    System.out.println("Successfully registered!");
                    
                    //Save username
                    new UserRecord().setUsername(username);
                    
                    new CafeMenu().setVisible(true);
                    this.dispose();
                }
                con.close();
                
            } catch (HeadlessException | ClassNotFoundException | SQLException e){
                System.out.println("Error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnPeekMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeekMousePressed
        tfPassword.setEchoChar((char)0);
    }//GEN-LAST:event_btnPeekMousePressed

    private void btnPeekMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeekMouseReleased
        tfPassword.setEchoChar('*');
    }//GEN-LAST:event_btnPeekMouseReleased
    
    private String hashPassword(String password) {
        try {
            MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = messageDigest.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Error: Could not hash password", e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CafeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPeek;
    public javax.swing.JTextField tfContactNo;
    public javax.swing.JTextField tfEmail;
    public javax.swing.JTextField tfFirstName;
    public javax.swing.JTextField tfLastName;
    public javax.swing.JPasswordField tfPassword;
    public javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
